---
- name: Instala e configura servidor dhcp.
  hosts: arq
  become: true

  vars:
    dhcp_name_pack:
      "Debian": isc-dhcp-server
      "RedHat": dhcp
    dhcp_name_serv:
      "Debian": isc-dhcp-server
      "RedHat": dhcpd

  handlers:
    - name: restart dhcp
      service:
        name: "{{ dhcp_name_serv[ansible_os_family] }}"
        state: restarted

  tasks:
    - name: Instala o servidor dhcp.
      package:
        name: "{{ dhcp_name_pack[ansible_os_family] }}"
        update_cache: yes
        state: present

    - name: Copia o arquivo de configuração dhcp.
      copy:
        src: "dhcpd.conf"
        dest: "/etc/dhcp/dhcpd.conf"
        mode: '0664'
      notify: restart dhcp

    - name: Habilita o serviço do dhcp.
      service:
        name: "{{ dhcp_name_serv[ansible_os_family] }}"
        enabled: yes

    - name: Ajusta a configuração default do dhcp.
      lineinfile:
        dest: "/etc/default/{{ dhcp_name_serv[ansible_os_family] }}"
        regexp: "^INTERFACESv4"
        line: 'INTERFACESv4="eth1"'
        state: present
      notify: restart dhcp

