---
- name: Configurar VM cli
  hosts: cli
  become: yes
  vars:
    nfs_server_ip: 192.168.56.107  # IP do servidor NFS (arq)

  tasks:
    - name: Instalar Firefox e xauth
      apt:
        name:
          - firefox-esr
          - xauth
        state: present
        update_cache: yes

    - name: Garantir que o OpenSSH Server está instalado
      apt:
        name: openssh-server
        state: present

    - name: Permitir o encaminhamento X11 no SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?X11Forwarding'
        line: 'X11Forwarding yes'
        state: present
        backup: yes

    - name: Garantir que X11UseLocalhost está habilitado corretamente
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?X11UseLocalhost'
        line: 'X11UseLocalhost no'
        state: present

    - name: Reiniciar o serviço SSH para aplicar alterações
      service:
        name: ssh
        state: restarted
        enabled: true

    - name: Instalar pacotes necessários
      apt:
        name: [nfs-common, autofs]
        state: present

    - name: Auto.master
      copy:
        dest: /etc/auto.master
        content: |
          /var/nfs /etc/auto.nfs --timeout=60

    - name: Auto.nfs
      copy:
        dest: /etc/auto.nfs
        content: |
          dados -rw,sync,soft,intr 192.168.56.107:/dados/nfs

    - name: Reiniciar autofs
      service:
        name: autofs
        state: restarted
        enabled: yes

    - name: Testar montagem manual (opcional)
      command: mount -t nfs 192.168.56.107:/dados/nfs /mnt
      when: true  # Alterar para true se quiser testar montagem manual
