---
- name: Configurar servidor web na VM app
  hosts: app
  become: yes
  vars:
    nfs_server_ip: 192.168.56.107   # IP do servidor NFS (arq)
    projeto_descricao: "Sistema de Compartilhamento de Arquivos via NFS"
    equipe_integrantes: |
      <ul>
        <li>Nome: Lucas dos Santos Carvalho - Matrícula: 20222380007</li>
        <li>Nome: Pedro Weverton Barbosa - Matrícula: 20222380020</li>
      </ul>

  tasks:
    - name: Instalar o servidor Apache2
      package:
        name: apache2
        state: present

    - name: Criar página index.html personalizada
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
            <head>
              <title>Projeto NFS - Equipe</title>
            </head>
            <body>
              <h1>{{ projeto_descricao }}</h1>
              <h2>Integrantes da Equipe</h2>
              {{ equipe_integrantes }}
            </body>
          </html>
        mode: '0644'
        owner: www-data
        group: www-data

    - name: Reiniciar Apache2
      service:
        name: apache2
        state: restarted
        enabled: true

    - name: Instalar o serviço autofs
      package:
        name: autofs
        state: present

    - name: Configurar /etc/auto.master
      copy:
        dest: /etc/auto.master
        content: |
          /var/nfs  /etc/auto.nfs

    - name: Configurar /etc/auto.nfs
      copy:
        dest: /etc/auto.nfs
        content: |
          dados  -rw,sync  {{ nfs_server_ip }}:/dados/nfs

    - name: Reiniciar o serviço autofs
      service:
        name: autofs
        state: restarted
        enabled: true

